name: ASP.NET Core CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.1.801', '2.2.108' ]
    runs-on: ${{ matrix.platform }}
    name: Dotnet ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build --configuration Release

