name: ASP.NET Core CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.1.801', '2.2.108' ]
    name: Dotnet ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@master
      - name: Build solution
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build --configuration Release
  test:
    runs-on: ubuntu-latest
    name: Test ${{ matrix.dotnet }}
    strategy:
      matrix:
        dotnet: [ '2.1.801', '2.2.108' ]
    steps:
    - uses: actions/checkout@master
    - name: dotnet test
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
      run: |
        dotnet build --configuration Release
        dotnet test ~/work/resilience-strategy-with-polly/resilience-strategy-with-polly/src/Resilience.Polly.Sql.Tests/Resilience.Polly.Sql.Tests.csproj
